version: '3.8'
services:
  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  pgadmin-data:
